version: '3.8'
services:
  traefik-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traefik-manager
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose-files:/var/www/html/compose-files
      - ./traefik-configs:/var/www/html/traefik-configs
    environment:
      DB_SERVER: db
      DB_NAME: traefik_manager
      DB_USERNAME: tm_user
      DB_PASSWORD: tm_password
      YAML_OUTPUT_PATH: /var/www/html/traefik-configs/dynamic.yml
    depends_on:
      - db
    networks:
      - traefik-manager-net

  db:
    image: mysql:8.0
    container_name: traefik-manager-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: traefik_manager
      MYSQL_USER: tm_user
      MYSQL_PASSWORD: tm_password
      MYSQL_ROOT_PASSWORD: root_password_change_me # Ganti ini dengan password yang aman
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - traefik-manager-net

networks:
  traefik-manager-net:
    driver: bridge

volumes:
  db_data:
    driver: local