<?php
// Router sudah menangani otentikasi dan otorisasi.
require_once __DIR__ . '/../includes/bootstrap.php';
$conn = Database::getInstance()->getConnection();

if (!isset($_GET['from']) || !isset($_GET['to'])) {
    header('location: ' . base_url('/history?status=error&message=Please select two versions to compare.'));
    exit;
}

$from_id = (int)$_GET['from'];
$to_id = (int)$_GET['to'];

function getHistoryContent($conn, $id) {
    $stmt = $conn->prepare("SELECT id, yaml_content, generated_by, created_at FROM config_history WHERE id = ?");
    $stmt->bind_param("i", $id);
    $stmt->execute();
    $result = $stmt->get_result();
    if ($row = $result->fetch_assoc()) {
        return $row;
    }
    return null;
}

$from_version = getHistoryContent($conn, $from_id);
$to_version = getHistoryContent($conn, $to_id);

if (!$from_version || !$to_version) {
    header('location: ' . base_url('/history?status=error&message=One or both selected versions could not be found.'));
    exit;
}

require_once __DIR__ . '/../includes/header.php';
?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Compare Deployments</h1>
    <a href="<?= base_url('/history') ?>" class="btn btn-sm btn-outline-secondary">Back to Deployment History</a>
</div>

<div class="row mb-3">
    <div class="col-md-6">
        <h5>Version #<?= $from_version['id'] ?> <small class="text-muted">(From)</small></h5>
        <p class="text-muted small mb-0">Generated by <?= htmlspecialchars($from_version['generated_by']) ?> at <?= $from_version['created_at'] ?></p>
    </div>
    <div class="col-md-6">
        <h5>Version #<?= $to_version['id'] ?> <small class="text-muted">(To)</small></h5>
        <p class="text-muted small mb-0">Generated by <?= htmlspecialchars($to_version['generated_by']) ?> at <?= $to_version['created_at'] ?></p>
    </div>
</div>

<div id="diff-output"></div>

<!-- Hidden pre tags to hold the content for JS -->
<pre id="from-content" style="display:none;"><?= htmlspecialchars($from_version['yaml_content']) ?></pre>
<pre id="to-content" style="display:none;"><?= htmlspecialchars($to_version['yaml_content']) ?></pre>

<?php
require_once __DIR__ . '/../includes/footer.php';
?>