<?php
// Router sudah menangani otentikasi dan otorisasi.
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/header.php';
?>

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Deployment History</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="form-check form-switch me-3">
            <input class="form-check-input" type="checkbox" role="switch" id="show-archived-checkbox">
            <label class="form-check-label" for="show-archived-checkbox">Show Archived</label>
        </div>
        <form class="search-form me-2" data-type="history">
            <div class="input-group input-group-sm">
                <input type="text" name="search_history" class="form-control" placeholder="Cari berdasarkan user...">
                <button class="btn btn-outline-secondary" type="submit" title="Search"><i class="bi bi-search"></i></button>
                <button class="btn btn-outline-secondary reset-search-btn" type="button" title="Reset"><i class="bi bi-x-lg"></i></button>
            </div>
        </form>
        <button id="compare-btn" class="btn btn-sm btn-outline-primary" disabled>
            <i class="bi bi-files"></i>
            Compare Selected (0)
        </button>
        <a href="<?= base_url('/history/cleanup') ?>" class="btn btn-sm btn-outline-danger ms-2" title="Cleanup old records">
            <i class="bi bi-trash3"></i> Cleanup
        </a>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-sm table-hover">
                <thead>
                    <tr>
                        <th><input class="form-check-input" type="checkbox" id="select-all-history"></th>
                        <th>ID</th>
                        <th>Generated At</th>
                        <th>Generated By</th>
                        <th>Status</th>
                        <th class="text-end">Actions</th>
                    </tr>
                </thead>
                <tbody id="history-container">
                    <!-- Data will be loaded by AJAX -->
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer d-flex justify-content-between align-items-center">
        <div class="text-muted small" id="history-info">
            <!-- Pagination info will be loaded here -->
        </div>
        <div class="d-flex align-items-center">
            <nav id="history-pagination">
                <!-- Pagination controls will be loaded here -->
            </nav>
            <div class="ms-3">
                <select name="limit_history" class="form-select form-select-sm limit-selector" data-type="history" style="width: auto;">
                    <option value="10">10</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    <option value="-1">All</option>
                </select>
            </div>
        </div>
    </div>
</div>

<!-- View History Modal is in footer.php -->

<?php
require_once __DIR__ . '/../includes/footer.php';
?>